---
# zpa_cloud_connector_group_info.yml - Get details (ID and/or Name) of a cloud connector group resource.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_cloud_connector_group_info' module to retrieve a Cloud Connector Group detail from the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables connection
# to the ZPA Cloud 'client_id', 'client_secret', customer_id and 'cloud'. These may be defined as host variables
# (see `host_vars/zpa_cloud.yml` for an example) or extra vars.
#
# Modules Used
# ============
#
# zpa_cloud_connector_group_info - https://zscaler.github.io/zpacloud-ansible/modules/zpa_cloud_connector_group_info_module.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_cloud_connector_group_info.yml

- name: Gather Details of Cloud Connector Groups
  hosts: localhost
  connection: local

  vars:
    zpa_cloud:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret | default(omit) }}"
      customer_id: "{{ customer_id | default(omit) }}"
      cloud: "{{ cloud | default(omit) }}"

  tasks:
    - name: Gather Information Details of All Cloud Connector Groups
      register: all_cloud_connector_groups
      willguibr.zpacloud.zpa_cloud_connector_group_info:
        provider: "{{ zpa_cloud }}"

    - name: All Cloud Connector Groups
      ansible.builtin.debug:
        msg: "{{ all_cloud_connector_groups }}"

    - name: Gather Information Details of a Cloud Connector Group by Name
      register: cloud_connector_group_name
      willguibr.zpacloud.zpa_cloud_connector_group_info:
        provider: "{{ zpa_cloud }}"
        name: zs-cc-vpc-096108eb5d9e68d71-ca-central-1a

    - name: Cloud Connector Groups By Name
      ansible.builtin.debug:
        msg: "{{ cloud_connector_group_name }}"

    - name: Gather Information Details of a Cloud Connector Group by ID
      register: cloud_connector_group_id
      willguibr.zpacloud.zpa_cloud_connector_group_info:
        provider: "{{ zpa_cloud }}"
        id: "216196257331292017"

    - name: Cloud Connector Groups By ID
      ansible.builtin.debug:
        msg: "{{ cloud_connector_group_id }}"
